services:
  - type: web
    name: chatify-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
